### ISSUE TITLE
Validate "type" column in *_channels.tsv

### ISSUE THREAD

**Issue by hoechenberger** [bids-standard/legacy-validator#1018]
Hello, while working with the  [OpenNeuro ds001810 dataset](https://openneuro.org/datasets/ds001810) (EEG data), I discovered that e.g. `sub-01/ses-anodalpre/eeg/sub-01_ses-anodalpre_task-attentionalblink_channels.tsv` looks like this:

```
name    type    units   sampling_frequency      description     status  status_description
...
PO4     eeg     uV      512     EEG channel     good    n/a
O2      eeg     uV      512     EEG channel     good    n/a
EXG1    eog     uV      512     above left eyebrow (VEOG1)      good    n/a
EXG2    eog     uV      512     below left eye (VEOG2)  good    n/a
EXG3    misc    uV      512     left earlobe (for re-referencing)       good    n/a
EXG4    misc    uV      512     right earlobe (for re-referencing)      good    n/a
...
Status  trig    unknown 512     triggers        good    n/a
```
(`...` added by me to indicate I have omitted lines)
As you can see, the values in the `type` column are all in lowercase letters. **This dataset passes validation.**

However, the [BIDS specification for EEG data](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/03-electroencephalography.html) demands **uppercase** spelling. So I suppose this is a rule that is currently not checked or enforced by the validator.

This has already caused an [issue](https://github.com/mne-tools/mne-bids/issues/481) for us downstream. I would therefore appreciate if this could be addressed.

Thanks for your help,

–Richard.

**Comment by jasmainak** [comment]
humm ... the specification doesn't say anywhere that uppercase is required. Or did I miss something?

**Comment by hoechenberger** [comment]
> humm ... the specification doesn't say anywhere that uppercase is required. Or did I miss something?

Yes, well, it doesn't say so in terms of literally stating, "use uppercase!"
But the table of valid channel types only contains uppercase spelling, and states that the list of keywords is "restricted" to those listed:

<img width="648" alt="Screenshot 2020-07-21 at 19 34 43" src="https://user-images.githubusercontent.com/2046265/88087525-57aaf080-cb89-11ea-8a9e-1062fe562775.png">

**Comment by sappelhoff** [comment]
Currently we are not even validating that the channel type comes from the list ... even when disregarding casing.

We need to add a new check similar to the one we have for checking the `status` column in `channels.tsv`:

https://github.com/bids-standard/bids-validator/blob/029e37e2d77702a9c130a365b5480c3a41461297/bids-validator/validators/tsv/checkStatusCol.js#L1-L37

when following that existing check and copying the logic, then I think this addition would be relatively manageable.

Also, it seems like in https://github.com/bids-standard/bids-specification/issues/534 people are converging towards enforcing upper case.


PS: I removed the bug label, because this is a coverage issue and implementing this request would be an enhancement (i.e., it's not like existing code is buggy)

**Comment by sappelhoff** [comment]
perhaps @adam2392 wants to give his JS skills a bump once more? :-)

**Comment by adam2392** [comment]
Sure, this seems pretty easy. 

1. Check against fixed set of variables (after upper-casing everything) -> error if any variable outside list
2. If any upper-casing was needed -> fire warning that you should use upper-casing

I also just fixed this lame installation of the dev version (on mac) due to having miniconda on your terminal at all times. One needs to add explicitly `sudo conda install nodejs=14.6.0`, which I can add to the `contributing.md` doc.

Lmk if the above sounds good and I can go ahead and implement sometime this weekend/next.
