### ISSUE TITLE
participants.tsv breaks web validator

### ISSUE THREAD

**Issue by oesteban** [bids-standard/legacy-validator#106]
This participants file breaks the validator when present in the root of the bids structure:
[participants.zip](https://github.com/INCF/bids-validator/files/185117/participants.zip)

**Comment by oesteban** [comment]
The command line works fine and reports this error:

Empty cell in TSV file detected: The proper way of labeling missing values is "n/a". (code: 23)

**Comment by oesteban** [comment]
More specifically, the chrome tab crashes :)

**Comment by constellates** [comment]
Thanks @oesteban.

I'm not 100% sure but I believe this is caused by using newer javascript language features that don't have great support in one of the newer checks

https://github.com/INCF/bids-validator/blob/master/validators/session.js#L50
https://github.com/INCF/bids-validator/blob/master/validators/session.js#L53

I'll see if that is indeed the cause and look into either poly filling or rewriting this.

**Comment by chrisgorgo** [comment]
BTW ds116 (which includes participants.tsv) works correctly (in the browser).

**Comment by constellates** [comment]
It looks like it's the specific participants.tsv linked above.

**Comment by chrisgorgo** [comment]
@oesteban I just tried the folder you attached (with just the participants.tsv file in the root). Browser version of the validator gives me "This does not appear to be a BIDS dataset. Select a new folder and try again." Which is the expected behaviour.

**Comment by constellates** [comment]
If you add the above participants.tsv to a valid dataset you can see the issue.

**Comment by oesteban** [comment]
If the participants.tsv does not contain empty cells, the web validator works well.

**Comment by constellates** [comment]
Ok it looks the this is caused by the browser choking trying to render too many issues. The validation code itself didn't fail. It caught 55697 instances of empty cells in that participants.tsv file and then the browser choked trying to render that many issues.

@chrisfilo are you ok with limiting how often we report this issue per file? I think the error message is descriptive enough that we could limit this to once per file and ignore the remaining instances.

```
Empty cell in TSV file detected: The proper way of labeling missing values is "n/a".
```

But we could probably use any sane limit (10-20) if that's preferred. Here's an example of how multiple instances are currently reported back to the user.

<img width="714" alt="screen shot 2016-03-23 at 10 59 58 am" src="https://cloud.githubusercontent.com/assets/4325905/13995429/71b807ce-f0e6-11e5-869f-cac38b9b2e17.png">

**Comment by constellates** [comment]
I just noticed a related bug to this issue. These tsv checks, for empty cells and mismatched rows, are the only ones I know of where we report multiple instances of the same issue in a single file. However, we don't account for this when displaying issues in the browser. Our data structure implies that each of these instances are separate files, so in the above image you can see "5 files" in the upper right, but every file is the same file with a different line an character. The CLI output is vague enough that this is less of an issue, but it could also be improved.

@chrisfilo Is it valuable to report multiple instances of the same issue in the same file or is one enough to alert the user to address the issue? If multiple instances are important we can create a list of the locations (lines/character descriptions), but this would require some sane limit as there were +55,000 instances of empty cells in the above example..

**Comment by chrisgorgo** [comment]
I think it would be reasonable to report it only once. Thanks for noticing
this!
