### ISSUE TITLE
Maximum call stack size exceeded; 

### ISSUE THREAD

**Issue by wangjinvandy** [bids-standard/legacy-validator#1063]
Our lab has very hug dataset and wants to share. However, it looks like it exceeds to maximum of the validator. Can you please increase the capacity of it?

RangeError: Maximum call stack size exceeded at Oi (https://bids-standard.github.io/bids-validator/_next/static/lcAFkzjYJB3Y9y9R5kJls/pages/index.js:1:1384136) at https://bids-standard.github.io/bids-validator/_next/static/lcAFkzjYJB3Y9y9R5kJls/pages/index.js:1:1396153

**Comment by effigies** [comment]
I assume the call stack is a function of the browser, and we're unlikely to have much control over that. For an environment where you can manipulate the heap size, I would suggest [installing the CLI](https://github.com/bids-standard/bids-validator#on-the-server).

**Comment by wangjinvandy** [comment]
Hi, Chris,

I used the docker approach (our server can only run singularity) and tried to run validator on our data stored on server. It still gives me the maximum call stack size exceed error. I cannot make the npm intall bids-validator work.  Do you have any suggestions for how to set the heap size for the docker approach?

Best
Jin


Jin Wang
Graduate Student
Psychology and Human Development,
Peabody College at Vanderbilt University
Office: Hobbs 425


________________________________

**Comment by effigies** [comment]
You can use `--entrypoint=bash` to get access to the CLI inside the Docker container, and then call `bids-validator` with the modified invocation.

**Comment by wangjinvandy** [comment]
Hi, Chris,

Thank you for your suggestion. However, I am not familiar with docker and singularity (nor npm, which I cannot install on our campus server). Is it possible that we can zoom so you can guide me on how to do it? If not, can you please send me a more detailed instructions on how to use singularity to change the docker container's CLI?

I goolged around whole day long but still haven't got anything working. Would be very appreciate it if you can help more. Thank you very much!


Best
Jin


Jin Wang
Graduate Student
Psychology and Human Development,
Peabody College at Vanderbilt University
Office: Hobbs 425


________________________________

**Comment by effigies** [comment]
@cdale8 Would you be able to provide an invocation that adjusts the stack size? I haven't played with this much, myself and I know you were working with this recently.

**Comment by hjmjohnson** [comment]
@effigies I am running into this problem with the command line interface.  Previous hack of
```
export NODE_OPTIONS="--max-old-space-size=32384"; 
```
and `--stack-size=10000` are not working.

**Comment by wangjinvandy** [comment]
Hello,

I haven't heard anything from you about the solutions for the call stack size error. But I separated my dataset into five chunks and validated chunk by chunk. I confirmed that our format is good with this chunk-by-chunk checking and plan to upload our data to openneuro.org now. So, I thought that our problem was solved by using this alternative approach.

However, after I combine my data to its original look and try to upload to openneuro.org using command-line cli https://www.npmjs.com/package/openneuro-cli?activeTab=readme. They said large data uploading is good with using the command line. However, I still get an error because it cannot go over the bids-validation section. The same error occurs here again (see attached). I sent an email to openneuro.org but I am not sure if the bids-validtor section is their responsibility or not. Maybe you can colaborate to solve it?

Thank you! Really looking forward to your reply. Otherwise our data cannot be shared.

Best
Jin


Jin Wang
Graduate Student
Psychology and Human Development,
Peabody College at Vanderbilt University
Office: Hobbs 425


________________________________

**Comment by nellh** [comment]
Could someone who is experiencing this issue provide a list of files in your dataset? We shouldn't need the actual files but having the directory structure and filenames would be very helpful. `find dataset_directory/ -print` will generate this list on Linux or macOS.

**Comment by effigies** [comment]
@wangjinvandy Can you try the suggestions @hjmjohnson made?

I will see about whether any paid developer time can be devoted to this issue. Unfortunately, there is not much volunteer JavaScript expertise in the community.

**Comment by wangjinvandy** [comment]
@effigies Hi, Chris, Thank you for your reply. Hopefully there will be someone helping upgrade the bids-validator capacity. I believe as the open science is the trend and sharing large dataset is also the trend. It would be a great contribution to science.

However, I am not sure what you mean by @hjmjohnson suggestion?  The following one? It is not clear if that works according to the following comment. Maybe I misunderstood something. 
"@effigies I am running into this problem with the command line interface. Previous hack of
export NODE_OPTIONS="--max-old-space-size=32384"; 
and --stack-size=10000 are not working."

**Comment by wangjinvandy** [comment]
> Could someone who is experiencing this issue provide a list of files in your dataset? We shouldn't need the actual files but having the directory structure and filenames would be very helpful. `find dataset_directory/ -print` will generate this list on Linux or macOS.

@nellh Hi, Nell, I attached the list here for your information. 
[filelist.txt](https://github.com/bids-standard/bids-validator/files/5359946/filelist.txt)

**Comment by cdale8** [comment]
Sorry for the long delay in response.  Here is the solution (not optimal) that our project is using:

We installed a singularity container with the command line version of bids-validator on our network.

I tested using the command line version with our very large study dataset while logged on to a variety of workstations with different memory capacities and found that the number/size of subject datasets that would successfully validate depended upon the workstation I used and none of these achieved anywhere near the web-based capacity of about 950GB of data.  I was not able to change stack size within the software, as I kept running into issues changing parameters in the singularity container combined with resources on particular workstations.

Because I can validate portions of the data on its own, I set up a second directory that softlinks to the participants.tsv, participants.json, dataset_description.json, etc. in the main BIDS directory, and every time I add a new subject to the study BIDS directory I softlink to that subject's directory in the second directory, then run bids-validator (command line, integrated into my data management pipeline now rather than manually doing it via the web tool, so there's that benefit) to ensure the new directory is bids compliant within the framework of the full study (without pulling in the first 1TB of subjects that were already validated).  This seems to be working for the current study.  The analysis pipeline for DTI and fMRI is only pulling in a few subjects at a time, and no one has reported issues (yet) with the various tools that require validation.

I don't know if that helps solve the problem for others, or helps at all in modifying code for the issue, but it may serve as a quick workaround for those with large studies.

**Comment by hjmjohnson** [comment]
Here is my listing:  
[Uploading validation_failure.list.gz…]()

**Comment by rwblair** [comment]
@cdale8 @wangjinvandy A new flag in 1.5.7 has been added, `--ignoreSubjectConsistency` this bypasses a set of checks that generates warnings about subjects having files or sessions that other subjects don't have. It allowed @hjmjohnson to validate their dataset that was hitting the stack size limit. If you try it out let me know how it goes.

**Comment by cdale8** [comment]
@rwblair Our project dataset will run through without the stack error, but the new version produces errors in handling MEG data, specifically in all the channels.tsv files.  As we are coded correctly for BIDS 1.2.2, and apparently the type options and syntax for MEG channels has changed (according to these new errors trigger, refgrad, megmag, aux, and misc are no longer valid MEG channel types, and should be in upper case), we will need to continue to use the 1.5.4 validator rather than re-code and re-run the data from the entire (ongoing) study.

**Comment by sappelhoff** [comment]
>  As we are coded correctly for BIDS 1.2.2, and apparently the type options and syntax for MEG channels has changed

just a small comment: The channel types were always meant to be upper case, however the specification was ambiguous about that and the validator did not properly validate the casing.

We caught this issue some weeks ago and improved the specification (no longer ambiguous) as well as the validator. This leads to some previously uncaught errors to now surface for some users. :slightly_frowning_face:

**Comment by cdale8** [comment]
Thanks @sappelhoff, it affects 237968 files in our BIDS directory and the .tsv files were created via a version of Fieldtrip that we froze for this project, so I'd have to recode at that level.  Next project...

**Comment by rwblair** [comment]
@cdale8 Thanks for the response. I had to write a gnarly bash/sed oneliner to fix the capitalization in the bids-examples which only affected a few dozen files. 237968 files is intense. I'll try and keep that number in mind as I read through the tsv validator.

**Comment by VisLab** [comment]
From @happy5214.....
 To follow up on the TSV issue, the files are loaded at
https://github.com/bids-standard/bids-validator/blob/556e86dff6e3b97249f3741bf76a8c5879d667ea/bids-validator/validators/tsv/validate.js#L23
<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbids-standard%2Fbids-validator%2Fblob%2F556e86dff6e3b97249f3741bf76a8c5879d667ea%2Fbids-validator%2Fvalidators%2Ftsv%2Fvalidate.js%23L23&data=02%7C01%7CKay.Robbins%40utsa.edu%7C5dfedc89138e444108b808d871f70240%7C3a228dfbc64744cb88357b20617fc906%7C0%7C1%7C637384652991953668&sdata=bHhySxF5DCEkwwJrNtJa5Sn%2BqIqwCrsyEyJgAPBzAa8%3D&reserved=0>.
It's within a function invoked as part of a map call on the files
parameter, which is traced back to the array populated at
https://github.com/bids-standard/bids-validator/blob/556e86dff6e3b97249f3741bf76a8c5879d667ea/bids-validator/validators/bids/groupFileTypes.js#L40
<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbids-standard%2Fbids-validator%2Fblob%2F556e86dff6e3b97249f3741bf76a8c5879d667ea%2Fbids-validator%2Fvalidators%2Fbids%2FgroupFileTypes.js%23L40&data=02%7C01%7CKay.Robbins%40utsa.edu%7C5dfedc89138e444108b808d871f70240%7C3a228dfbc64744cb88357b20617fc906%7C0%7C1%7C637384652991963660&sdata=hw3gozitcysWorTfhaoePZe45s7xJMQL6RocNX44d1I%3D&reserved=0>.
It comprises all files in the dataset with the extension .tsv. It performs
a set of TSV validation checks on these files.


My understanding is that the tsv files are all read in. There was some
discussion about just reading in the tsv headers. Event files will
eventually need to be read in their entirety, but they only need to be kept
in memory while they are individually validated. It seems like it might be
reasonable to reorganize the current code so that it just accumulates the
file names uses "lazy reading".  Tsv files for other modalities have the
potential to be huge.
