### ISSUE TITLE
bidsignore is being abused to smuggle non BIDS data into OpenNeuro

### ISSUE THREAD

**Issue by arnodelorme** [bids-standard/legacy-validator#1103]
Below the EEG is contained in custom .mat files that do not use a particular format

https://openneuro.org/datasets/ds002725/versions/1.0.0

This is not consistent with the EEG BIDS definition, yet it passed validation

https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/03-electroencephalography.html

**Comment by sappelhoff** [comment]
Hi @arnodelorme could you point us to the files that you are talking about by for example, providing a relative path in ds002725 ?

I cloned the dataset and ran `find . -type f -name "*.mat*"` but could not find any `.mat` files.

Are you suggesting that the edf files from ds002725 are actually mat files where somebody just replaced ".mat" with ".edf"?

That would be evil ... :thinking:

**Comment by arnodelorme** [comment]
I meant ds002739

See sub-01/EEG/sub-01_EEG_EEG_data_sub-01_run-01.mat

**Comment by sappelhoff** [comment]
In that case the answer is: "because the dataset curator has *bids-ignored* the EEG data":

see their [bidsignore file](https://openneuro.org/datasets/ds002739/versions/1.0.0/file-display/.bidsignore):

```
/sub-*/EEG/**
/additional_files/**
```

The validator is acting as expected here. However there could be a discussion about restricting bidsignore.

In any case, a message to the dataset curator may be in order, because datasets like that are of little use on openneuro (IMHO).

**Comment by arnodelorme** [comment]
OK, I will let Franklin know,

Arno

**Comment by sappelhoff** [comment]
@arnodelorme I have also taken the liberty to rename your issue to: "bidsignore is being abused to smuggle non BIDS data into OpenNeuro"

cc @franklin-feingold @effigies @rwblair 

Also @jasmainak, who has often complained that `bidsignore` allows users to do "Whatever the fuck they want".

**Comment by effigies** [comment]
The entire point of `.bidsignore` is to "smuggle" non-BIDS data into BIDS datasets. BIDS is inherently a work-in-progress and the only way to allow a researcher to upload a complete description of a study containing as-yet-unstandardized data is to ignore that data. Some people have used `sourcedata/` to hide their non-standard files, some `derivatives/`, and some use `.bidsignore`.

There are definitely cases that go too far, but this is actually not one of them. This was a dataset that predated the BIDS-EEG extension. (It was taken down and reuploaded this year due to the discovery of possible PHI.) The only recourse for this sort of situation is to prevail upon the contributors to update their dataset with the new standards. In this case, the contributors are unresponsive, so our options are either to find an expert willing to help us convert the data into a standard form or simply accept that the dataset is not a BIDS-EEG dataset but a BIDS-MRI dataset with some non-standard data included for completeness. We would need to think carefully about the precedents we're setting with opening datasets to third-party improvements without original contributor approval, but that's an OpenNeuro issue, not bids-validator.

Regarding abuse of `.bidsignore`, we have some related issues: https://github.com/OpenNeuroOrg/openneuro/issues/1199, https://github.com/bids-standard/bids-validator/issues/844

I would be happy to see a (configurable) flag to limit `.bidsignore`d files to some file count, total file size, or proportion of total dataset file count or size. I am not yet familiar enough with the code base to propose a mechanism, and previous discussions have not led to anybody proposing or critiquing a heuristic.

I would also be okay with setting restrictions on the entries to `.bidsignore` to prevent over-broad ignores. This could let us require users to say more specifically `sub-*/EEG/*.mat`, and give us the chance to identify likely misuses. I'm not really sure how plausible that is.

**Comment by sappelhoff** [comment]
>  This was a dataset that predated the BIDS-EEG extension.

I wasn't aware of that, and that changes my evaluation of the situation: It's understandable and acceptable that in the past datasets tried to "hack" support for not-then-existing extensions in order to share the full data.

I was under the impression that in our case here, somebody "hacked" the EEG support in order to bypass the now-existing validation. However that is not the case.

Finally: It's true that it's hard to hold dataset curators accountable for their datasets indefinitely, asking them to update and mirror all changes everywhere. And that's not a bids-validator issue either.

In fact, we are struggling with the same issue on bids-standard/bids-examples - and that's already a much smaller scope than OpenNeuro.

> Regarding abuse of .bidsignore, we have some related issues: OpenNeuroOrg/openneuro#1199, bids-standard/bids-validator#75

Thanks, these were the ones I had in mind.


I suggest to:

1. contact the dataset owners of ds002739 whether they'd be willing to update their dataset (but I won't do it myself)
1. close this issue, because it's not a bids-validator shortcoming
1. continue the discussion on better `.bidsignore` mechanisms in OpenNeuroOrg/openneuro#1199, bids-standard/bids-validator#75

The question on holding dataset curators accountable (or not, or to which degree) should also be held elsewhere. For example here: https://github.com/bids-standard/bids-examples/issues/208

**Comment by effigies** [comment]
> 1. contact the dataset owners of ds002739 whether they'd be willing to update their dataset (but I won't do it myself)

@franklin-feingold has tried. Apologies for not making that clear. This issue has been spread over multiple communication channels.

> 2. close this issue, because it's not a bids-validator shortcoming

Doing so now.

> 3. continue the discussion on better `.bidsignore` mechanisms in [OpenNeuroOrg/openneuro#1199](https://github.com/OpenNeuroOrg/openneuro/issues/1199), bids-standard/bids-validator#75

Sounds good.

**Comment by arnodelorme** [comment]
I think the EEG data should be moved to sourcedata in this case, otherwise people will get confused as to why it is not properly formatted.

Also it was resubmitted/re-uploaded way after BIDS EEG appeared 24 April 2020.

**Comment by franklin-feingold** [comment]
perhaps a minor clarification - this dataset was originally shared on September 24, 2018; prior to the BIDS-EEG standard coming online. The reupload was to address a possible PHI case.

**Comment by arnodelorme** [comment]
We can reformat the EEG so it is properly formatted. 
There are undocumented fields in the EEG data file though, and if the author does not respond, data will be lost (but it is unusable anyway).
Here is an EEG data file.

              Y: [63×1601780 double]
           chnan: [1×64 double]
    crr_channels: {1×30 cell}
              fd: 1000
              fs: 5000
             fsr: 5
          nanidx: []

What is crr_channels? What is fd? What is fsr?

Not sure it is worth our time but if it is truly a fMRI/EEG simultaneously acquired dataset, it is valuable to the community.
