### ISSUE TITLE
PET BIDS ScanDate field validation needs to be updated.

### ISSUE THREAD

**Issue by chrisrj** [bids-standard/legacy-validator#1154]
Hi,
There is an issue with the Scandate field validation.
According to the currently rendered draft of the PET BIDS specification, 
the "date of scan" field  Scandate format is:
(not the best date format: it is a bit unusual)
yyyy:mm:dd

This is not matched by the pattern
    "ScanDate": {
      "type": "string",
      "pattern": "^(?:2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$"
    },
in the pet.json schema.

Best wishes,
Christian
CC @mnoergaard @melanieganz

**Comment by sappelhoff** [comment]
Thanks for reporting @chrisrj, you are talking about this: https://bids-specification.readthedocs.io/en/bep-009/04-modality-specific-files/09-positron-emission-tomography.html#time

screenshot:

![image](https://user-images.githubusercontent.com/9084751/107007959-7ffbe480-6793-11eb-9197-9775c0830f85.png)


I actually think this should be fixed in the PET proposal. We already have a way to specify dates in BIDS following the [RFC3339](https://tools.ietf.org/html/rfc3339) specification closely (but not 100% exactly).

So IMHO, ScanDate should be specified as `YYYY-MM-DD[Z]` with the `Z` indicator being optional to say "this is in UTC timezone".

as described in [Units](https://bids-specification.readthedocs.io/en/bep-009/02-common-principles.html#units)
