### ISSUE TITLE
Publish to npm only if version has changed

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#121]

**Comment by constellates** [comment]
This is fixed.

When we were debugging the build last week we changed this line 

```
npm run npmPublish
```

to 

```
npm publish
```

It turns out that command was our strategy for not publishing if the version hadn't changed, but it was failing because it relies on an npm package `publish` that was being removed during the gh-pages smoke test. So I added it back and added a line to re-install that dependency before trying to publish.

**Comment by chrisgorgo** [comment]
Mystery solved! Thanks!
