### ISSUE TITLE
Misleading "No BIDS compatible data found for at least one subject" error

### ISSUE THREAD

**Issue by noah10** [bids-standard/legacy-validator#1226]
If you create a BIDS dataset that has a phenotype file (e.g. phenotype/NIH_Cognition_summary.tsv) with two participant id's (say 100 and 101) in it, but only have a subject directory for one of them (say 100) you'll get the following error (from v1.6.2 of the validator):

```
[ERR] No BIDS compatible data found for at least one subject. (code: 67 - NO_VALID_DATA_FOUND_FOR_SUBJECT)
		./sub-100
```

...despite the fact that BIDS-compatible data are in fact there for subject 100 - they're actually missing for subject 101. Remove the phenotype file and the error goes away.

(Interestingly, this doesn't happen if you have a participant id in the participants.tsv file that doesn't have a corresponding subject directory.)

The error message should ideally list the id's that lack subject directories, but it definitely should not list directories that do, in fact, have BIDS-compatible data.

**Comment by sappelhoff** [comment]
Thanks for the report @noah10 could you perhaps attach the dataset as a zip file? That'd help the future debuggers of this issue, and it sounds like the dataset is currently small /anonymous enough to upload it here.

**Comment by noah10** [comment]
Here you go.
[bids-bug-1226.zip](https://github.com/bids-standard/bids-validator/files/6132492/bids-bug-1226.zip)

**Comment by sappelhoff** [comment]
I finally found a minute and could replicate your error. Thanks.

I think the error sits around here: https://github.com/bids-standard/bids-validator/blob/1f50c70526877321d3a51afc311ddf854c9def1a/bids-validator/validators/bids/fullTest.js#L169-L173

when I add a `console.log(summary.subjects)` on line 169, it tells me `[ '5006' ]` as expected with your test dataset.
Then adding the same thing on line 173, it returns an empty list `[ ]` so somehow `tsv.checkPhenotype(phenotypeParticipants, summary)` is operating on the `summary`, which it probably shouldn't.

Because then, with the purged `summary.subjects`, the error that you run into is raised further below, namely here:

https://github.com/bids-standard/bids-validator/blob/1f50c70526877321d3a51afc311ddf854c9def1a/bids-validator/validators/bids/fullTest.js#L202-L205

I'll see if I can find a fix.

---

apart from that, I found that the rows in under your `participant_id` column in `phenotype/` do not follow the `sub-<label>` pattern and simply use `label`. You could fix that as well :-)

**Comment by sappelhoff** [comment]
okay, I found it @noah10 you may try to work with https://github.com/bids-standard/bids-validator/pull/1239 ... or wait until we manage to add that fix to the development branch (`master`) and eventually release it. :-)

**Comment by noah10** [comment]
Many thanks - glad to see this fixed. (And thanks also for the tip on the phenotype files!)
