### ISSUE TITLE
Web version works but python not

### ISSUE THREAD

**Issue by seralouk** [bids-standard/legacy-validator#1237]
I have just created a bids structure using `heudiconv` command.

I tried to validate the output using 1) the website https://bids-standard.github.io/bids-validator/ and 2) using the python package and 3) using `bids-validator`.

Using the website & `bids-validator` the bids structure is confirmed however, using Python `BIDSValidator().is_bids('path/to/bids/')` returns `False`. On the website, I pointed the path to the `bids` folder as I did using python.

<img width="1120" alt="Screenshot 2021-03-25 at 11 08 59" src="https://user-images.githubusercontent.com/25902670/112455946-8271c800-8d5a-11eb-8746-f088b4d65ed5.png">

<img width="1255" alt="Screenshot 2021-03-25 at 11 10 11" src="https://user-images.githubusercontent.com/25902670/112456075-adf4b280-8d5a-11eb-8656-4cd4033a7be0.png">

<img width="1541" alt="image" src="https://user-images.githubusercontent.com/25902670/112456855-70445980-8d5b-11eb-9c30-930b07093e6c.png">

**Comment by sappelhoff** [comment]
Hi @seralouk this is to be expected, because the python based bids-validator is very rudimentary and can only tell you if a single file is BIDS compliant. See the documentation (RADME):

> There are is a limited library of helper functions written in Python. The main function determines if a file extension is compliant with the BIDS specification.

and especially the example that comes next.

https://github.com/bids-standard/bids-validator#python-library

Screenshot:

![image](https://user-images.githubusercontent.com/9084751/112457086-b5688b80-8d5b-11eb-822c-74d3c043ca0f.png)

**Comment by seralouk** [comment]
Got it thanks! Not really trivial though. I would expect to path the path and get the validation. Thanks for clarifying this
