### ISSUE TITLE
Add support for data dictionaries

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#133]
See:
https://docs.google.com/document/d/1HFUkAEE-pB-angVcYe6pf_-fVf4sCpOHKesUvfb8Grc/edit#heading=h.r85srnfs3y24

Maybe we can start using JSOn schemas in this case.

**Comment by constellates** [comment]
What's important to test in this case?
- Allow `.json` files that have the same name as a `.tsv` file in the same directory.
- Do these `.json` files need to describe every column in the corresponding `.tsv` or can they describe any number of the present columns?
- Are any of the descriptors (LongName, Descriptions, Levels, etc) required or are they all optional?
- If levels are provided do we want test every value in the `.tsv` to ensure it matches one of the possible levels?

**Comment by chrisgorgo** [comment]
For now let's just do a minimal set of checks:
- Allow `.json` files that have the same name as a `.tsv` file in the same directory. (including hierarchies - so for example `/sub-01/func/sub-01_task-nback_events.tsv` can have one json file for all subjects in `/task-nback_events.json`)
- Check if json is a valid json

**Comment by constellates** [comment]
I've tested out a few data dictionaries on different modalities/levels and I believe the minimal checks are already covered by the current validations. All JSON files get validated as JSON files and the inheritance principle of BIDS allows them in any directory level so long as they follow the BIDS naming scheme.

Let me know if I missed anything or you'd like to add anything, otherwise I believe the minimal checks are in place.

**Comment by chrisgorgo** [comment]
I guess the only thing remaining would be adding the .json files (accompanying .tsv files) to the filename heuristics: https://github.com/INCF/bids-validator/blob/master/utils/type.js

**Comment by constellates** [comment]
That should have been obvious and the above PR should cover that.
