### ISSUE TITLE
MRI sidecar parameters may not be getting type-checked

### ISSUE THREAD

**Issue by effigies** [bids-standard/legacy-validator#1534]
This example has been brought to my attention: https://openneuro.org/datasets/ds002687/versions/1.2.0/file-display/task-VLD_bold.json

```JSON
    "PartialFourier": "6/8",
```

This should be fixed when we move to the schema validation, as the parameter is a `number` in the schema.

There are likely other things not getting type-checked. Should we quickly generate JSON schema and apply it, or would it be better to wait for the schema?

**Comment by sappelhoff** [comment]
I think we should generate JSON schemas and apply them -- if it leads to breakage now, it'll also lead to breakage later when the schema-based validator comes around. Better to break soon than later IMHO.

**Comment by rwblair** [comment]
Passes now because bold allows additionalProperties (by not specifying it) and then doesn't mention `PartialFourier` as a property explicitly:
https://github.com/bids-standard/bids-validator/blob/master/bids-validator/validators/json/schemas/bold.json

Most other json schemas explicitly forbid additional props.
