### ISSUE TITLE
Valid dataset that should not be

### ISSUE THREAD

**Issue by arnodelorme** [bids-standard/legacy-validator#1587]
This dataset appears as valid

https://openneuro.org/datasets/ds001784/versions/1.1.2

Yet, it is not valid. The EEG folder does not contain one of the 4 accepted format. It contains an MEG file format. If the folder was named MEG, it would be valid (even though this is EEG data, MEG folder can contain EEG data).

**Comment by effigies** [comment]
This is not a validator error; it looks like they're using bidsignore to shoehorn their data into OpenNeuro rather than conform their data. This is a violation of [OpenNeuro policies](https://docs.openneuro.org/policy/data_retention.html#manual-review-and-deletion).

The simplest thing would be to work with the authors to correct the error and release a new version.
