### ISSUE TITLE
Validator not reporting missing PhaseEncodingDirection

### ISSUE THREAD

**Issue by araikes** [bids-standard/legacy-validator#1601]
Question: 

I have a large multi-site dataset where I have DWI data that I obtained from another group. Some of the JSONs for the DWI do not report the PhaseEncodingDirection, only the PhaseEncodingAxis. However, this does not trigger a warning/error about the missing information. Should I be getting a warning?

Thanks

**Comment by effigies** [comment]
In general, it should be a warning if recommended and an error if required. The validator up to now has not been very consistent about warnings for missing recommended values, as each one required a specific rule, so it's possible that missing PhaseEncodingDirections were never warned.

The next version based on the BIDS schema will consistently generate these reports because it will be using the same source as the specification itself. At this point, I would consider a PR if someone wants to make one, but we will not put in development time introducing features that will be added with schema-based validation.

**Comment by araikes** [comment]
@effigies,

Thanks for the response. I can live without the validator throwing errors until the schema-based validation. I just wondered if I was expecting too much of it (which I was, apparently).

Thanks
