### ISSUE TITLE
Bids-validator does not flag differences in phase encoding direction

### ISSUE THREAD

**Issue by halmgren** [bids-standard/legacy-validator#1678]
Bids-validator (v1.11.0) does not flag differences in phase encoding directions (stored in json-sidecars) between subjects, which is important to know.

**Comment by effigies** [comment]
This would be a very expensive check to implement in the validator architecture, and it would have to be a warning because it is not a violation of BIDS. I think there is room for small focused tools that check for consistency or other things that are just beyond the scope of the validator. You can check out https://github.com/openneuroorg/miniqc for one such tool.

**Comment by halmgren** [comment]
Great, thanks for the link!
