### ISSUE TITLE
Validator generates multiple errors for one error in the bids dataset

### ISSUE THREAD

**Issue by sreekanthkura7** [bids-standard/legacy-validator#1686]
In some cases, BIDS validator is generating multiple errors for one error in the BIDS dataset. For example, in the below image, BIDS validator saying that there is one error in 5 files but there is only one error in one file. In the below case, _NIRSCoordinateSystem_ field in the  _sub-01_ses-02_coordsystem.json_ file is empty, which should not be. After adding appropriate value to that field, BIDS validator generates no errors. Is this something that can be fixed in the validator.

![BIDS_validation_error](https://github.com/bids-standard/bids-validator/assets/29243826/04a74d6f-e8d8-4a3c-8fd3-eff162db7e2a)

Thanks!

**Comment by rwblair** [comment]
This is a peculiarity of the json schema validator we use. The NIRSCoordinateSystem is allowed to be a value (`anyOf` in json schema) from one of four different sets of enumerations of values, (`enum` in json schema). So the validator generates errors for not finding a value in each of the four arrays, and then a final one because none of the four worked. When a good value is present it throws away the not found errors for the three other arrays since one good one was found. 

Not pretty I know, we are working on a rewrite of the validator that won't have this issue, so there are no plans to fix this as of now.
