### ISSUE TITLE
Software filter error for EEG file - yet software filter is defined

### ISSUE THREAD

**Issue by arnodelorme** [bids-standard/legacy-validator#1808]
This is one of the JSON file

```
{
    "TaskName": "WorkingMemory",
    "EEGReference": "common",
    "RecordingType": "continuous",
    "RecordingDuration": 486.545,
    "SamplingFrequency": 250.0,
    "EEGChannelCount": 67,
    "EOGChannelCount": 0,
    "PowerLineFrequency": 60,
    "SoftwareFilters": "n/a"
}
```

And this is the error

![Screen Shot 2023-09-19 at 9 26 32 AM](https://github.com/bids-standard/bids-validator/assets/1872705/028e541b-6202-41f5-b813-2d59dbfcb902)

This is the BIDS dataset (data has been stripped out)

https://drive.google.com/drive/folders/1U4SZ8osxU4eWFhkhs3F7cAlMfhBnGRgq?usp=sharing

This dataset will pass the old validator.

**Comment by rwblair** [comment]
This is on openneuro staging correct?

Most up to date schema isn't loading because of cors failure. Be nice of us to print schema version used some where.

Wasn't able to access google drive dataset but https://github.com/bids-standard/bids-examples/tree/master/ieeg_epilepsyNWB has `"SoftwareFilters": "n/a"` and generates same error on staging.

**Comment by effigies** [comment]
I believe this is fixed.
