### ISSUE TITLE
validator fails when funding is a list rather than a single string

### ISSUE THREAD

**Issue by poldrack** [bids-standard/legacy-validator#314]
with the following in dataset_description.json:

   "Funding": [
        "TODO",
        "GRANT #1",
        "GRANT #2"
    ],

I get:

	1: JSON file is not formatted according the the schema. (code: 55 - JSON_SCHEMA_VALIDATION_ERROR)
		./dataset_description.json
			Evidence: .Funding should be string

when it's changed to a string rather than a list, the validation is fine.

validation should be changed to accept either a string or a list of strings.

**Comment by suyashdb** [comment]
@poldrack  @chrisfilo Though not clearly mentioned in the spec if it should be list or string, wouldn't it be better if its list of string similar to authors..?
I mean to have just one option i.e list of strings..

**Comment by chrisgorgo** [comment]
Yes, a list would be better. Let's clarify this in the spec.

On Sep 27, 2017 2:21 AM, "Suyash" <notifications@github.com> wrote:

@poldrack <https://github.com/poldrack> @chrisfilo
<https://github.com/chrisfilo> Though not clearly mentioned in the spec if
it should be list or string, wouldn't it be better if its list of string
similar to authors..?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/INCF/bids-validator/issues/314#issuecomment-332381066>,
or mute the thread
