### ISSUE TITLE
Check if repetition time defined in the nifti header is the same as the one in corresponding JSON file.

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#34]

**Comment by constellates** [comment]
I'm testing out reading the headers with this library https://github.com/scijs/nifti-js . So far I've only tested two files (ds001/sub-01/anat/sub-01_inplaneT2.nii.gz and ds001/sub-01/anat/sub-01_T1w.nii.gz). Here's an example of what that library is extracting. I don't see repetition time? Do you know if those particular files don't contain it or if that's a limitation of the library?

```
{
    "dimension": 3,
    "type": "int16",
    "encoding": "raw",
    "endian": "little",
    "sizes": [
        128,
        128,
        33
    ],
    "spaceUnits": [
        "mm",
        "mm",
        "mm"
    ],
    "spacings": [
        1.5625,
        1.5625,
        4
    ],
    "spaceDimension": 3,
    "buffer": {},
    "data": {...}
}
```

It also appears that this library doesn't support partial file reads (i.e. reading and parsing the first 1000 bytes). So I haven't been able to test any of the larger functional scans due to memory limitations.

Do you know of any other javascript libraries that parse nifti binaries? And if not do you know where to find the specification for how the binary data is encoded? I found a link to this NIH side that appears to be down. http://nifti.nimh.nih.gov/

**Comment by constellates** [comment]
Adding this for reference. It looks to be a good resource for understanding the nifti format http://brainder.org/2012/09/23/the-nifti-file-format/

**Comment by chrisgorgo** [comment]
Yes - Anderson did a great job writing this up. To answer your questions:
- RepetitionTime only makes sense for _dwi and _bold files (they are 4 dimensional)
- I don't know of any other npm installable nifti reading library. I agree we should try to read only the header. If not to complicated we should enhance the nifti-js library by this feature or publish our own nifti reading library. There are some other JS based project that have nifti reading support built in that we can use for inspiration: https://github.com/rii-mango/Papaya and https://github.com/xtk/X

**Comment by constellates** [comment]
I've had some luck this morning getting nifti-js to only read through the header values. However, now I might need some help understanding how to get the repetition time from the header. Anderson lists out all of the header values and their location/size on that write up. Repetition time isn't mentioned in the header list. Is this a value that I need to interpret from other values or does it actually exist in the header somewhere I'm not seeing?

**Comment by constellates** [comment]
Ok. I think I'm getting the hang of this. I forked the nifti-js library (https://github.com/Squishymedia/nifti-header) and was able to get some more values from the header. 

```
{
    "dimension": 4,
    "type": "int16",
    "encoding": "raw",
    "endian": "little",
    "sizes": [
        64,
        64,
        33,
        300
    ],
    "spaceUnits": [
        "mm",
        "mm",
        "mm",
        "s"
    ],
    "spacings": [
        3.125,
        3.125,
        4,
        1
    ],
    "spaceDimension": 3,
    "buffer": {},
    "intent_p1": 0,
    "intent_p2": 0,
    "intent_p3": 0,
    "intent_code": 0,
    "datatype": "int16",
    "bitpix": 16,
    "slice_start": 0,
    "pixdim": [
        0,
        3.125,
        3.125,
        4,
        1
    ],
    "vox_offset": 352,
    "scl_slope": 1,
    "scl_inter": 0,
    "slice_end": 0,
    "slice_code": 0,
    "xyzt_units": [
        "mm",
        "mm",
        "mm",
        "s"
    ],
    "cal_max": 0,
    "cal_min": 0,
    "slice_duration": 0,
    "toffset": 0,
    "descrip": "FSL4.0\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
    "aux_file": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
    "qform_code": 0,
    "sform_code": 0,
    "quatern_b": 0,
    "quatern_c": 0,
    "quatern_d": 0,
    "qoffset_x": 0,
    "qoffset_y": 0,
    "qoffset_z": 0
}
```

Is my understanding correct that pixdim[4] is the repetition time and xyzt_units[3] is the corresponding unit for repetition time? 

I'll spend a little time cleaning up the output of the nifti-header lib so it outputs values with the same names they're defined with in the nifti specification. I haven't yet published it to npm or anything so let me know if you have any thoughts about how we should position this library. For example, should we keep it focused on nifti headers or rename and expand it to include other values.

**Comment by chrisgorgo** [comment]
Yes - this is the correct way of reading repetition time. Mind that some files (for example structural scans: _T1w.nii.gz) will be 3D so will not have fourth dimension defined.

In terms of disseminating this code the most sense would be sending a PR to https://github.com/scijs/nifti-js with the functionality you added. Hopefully the maintainer would be able to merge it and push it to npm. If that will not happen we should publish our own fork.

**Comment by constellates** [comment]
Alright I've got a pull request in with the nifti-js library to make that a little more flexible. The maintainer has been super responsive so that should go through and be a useful library if we need more data later on. It also supports outputting the header in NRRD format. I don't know too much about that format but it seems somewhat more future proof and interoperable with other systems.

I've built out header only nifti reading that works in the browser and server and I've built out the repetition time checks on a branch called "nifti-header". There's just a couple of things to wrap up.

The big one is figuring out a testing strategy. Now that we're relying on NIfTI file contents, the core BIDS test fails due to the empty scan files. Does it sound realistic to update the test data to include header data? The header exists in the first 348 bytes of the file so that how big the files would need to be. If you have the originals you or I could probably write a script to rewrite the scans to only contain the headers. Let me know if you would like to try that out or we can try to suppress those errors during the core bids test.

The other thing I wanted to check with you is a couple assumptions that I've made in the checks. The first being that the nifti format supports the following units for the time dimension.

```
s
ms
us
Hz
ppm
rad/s
```

I set the check up so if the time is in milliseconds or microseconds it will convert the value to seconds before checking if it matches the JSON value. Which also means we're not forcing users to define it in seconds like they have to in the JSON file.

If it's defined in any of the other units I'm throwing an error. Do we need to accommodate those other units for the scan time dimension?

And lastly here are the new errors that I've written. All of them are currently considered errors and the last one will also include the json location message.

```
We were unable to read the contents of this file.

Repetition time was not defined in seconds, milliseconds or microseconds in the scan's header. 

Repetition time did not match between the scan's header and the associated JSON metadata file.
```

Let me know if you'd like me to change any of the error language or if any of these should be considered warnings instead.

**Comment by constellates** [comment]
I also forgot to mention that with the dataset ds001 repetition time is showing up as 1 second in the header and 2 seconds in the sidecar. Do you know of another tool to read nifti headers so I can check if this is an issue with the dataset or with the nifti-js library?

**Comment by chrisgorgo** [comment]
Great job!

a) Yes seconds, milliseconds or microseconds are the only valid units.
b) I believe this dataset is indeed suffering with incorrect times in the headers. You can check these things using this viewer: http://ric.uthscsa.edu/mango/
c) testing - we can indeed create datasets with only headers, but it would be easier if we had a argument disabling header testing that we would use for datasets and include a couple of nifti files to test just the header validation.

**Comment by lrq3000** [comment]
Just my two cents: there are some converters that do not conserve the time of repetition info when converted to nifti but split in two files (hdr/img), because then the volumes are not 4D but 3D, and it seems some converters then "forget" to add the time of repetition.

**Comment by chrisgorgo** [comment]
BIDS requires 4D .nii[.gz] (not a pair of hdr/img) files. We recommend the excellent [dcm2niix](https://github.com/rordenlab/dcm2niix) (which also generate BIDS compatible JSON files).
