### ISSUE TITLE
fif.gz is allowed even though not mentioned in the spec

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#491]
We should either remove it or adjust the spec.

**Comment by sappelhoff** [comment]
+1 for adjusting the spec and continue to allow for .fif.gz. Compression is a good feature.

**Comment by jasmainak** [comment]
why not, but the corresponding datasets are also going to be updated I presume?

**Comment by ftadel** [comment]
I don't think we should encourage people to compress their MEG recordings (no matter which file format is used). Maybe it's a bit radical, but I'd be more in favor of not supporting .fif.gz extensions.

The .fif files have low compression ratios, between 10% and 15%. It saves some storage space, but to the expense of the usability of the datasets. To process the MEG recordings, they need to be fully unzipped first, which takes a lot of time and doubles the storage space needed. The gain in storage is negligible compared to the complexity of handling these compressed files.

The question is not the same for .nii files: these are small files with high compression ratios (up to 75%) that can be uncompressed in memory on the fly.

If compression has to be added to MEG recordings, it should be done within the file formats (it would be possible to add some compression to the .fif files), not simply by gzipping them.

**Comment by guiomar** [comment]
Thanks @ftadel, I was going to reply very similar.

I think this topic was raised a while ago, and we finally decided not to allow compressed *.gz files for MEG, for the reasons given above by @ftadel . So we finally didn't include this format in the specs for MEG.
I don't think it makes sense to reopen the discussion again, unless someone has a very strong opinion. For what I remember there was quite big consensus.

However, it's true this is not contemplated in the validator, so this needs to be fixed.
I will also make it more explicit in the specs.

((We are only speaking for MEG data))

Cheers!

**Comment by sappelhoff** [comment]
thanks @ftadel for the more nuanced view, I wasn't aware of previous discussions. :-)

**Comment by jasmainak** [comment]
I agree with @ftadel but someone has to update the corresponding dataset. Currently, the files in ds000117 are in `fif.gz` format :-)

**Comment by ftadel** [comment]
Rik is working on it. He will also add the missing Freesurfer folders and some fields in the json files.

**Comment by agramfort** [comment]
I agree with @ftadel you won't get much with fif.gz for raw files and it significantly slows down the IO or requires to duplicate files on disk.

**Comment by ftadel** [comment]
Erratum:
I've just unzipped all the .fif.gz files in ds000117 and realized that my initial tests were not fully representative. Different file type have different compression ratios:

 - Original .fif files: Compression ratios of around 70% (it saves 30% of the disk space - somewhat interesting).
 - SSS-processed .fif files (in derivatives folder): Compression ratios of around 85% (only 15% space saved - never recommended)
 - Empty-room recordings: Compression ratios around 50% (Interesting but very small files, negligible in the entire dataset)

Even with these new observtions, I would not recommend gzipping these files because of the added complexity to handle and process them. If we have to unzip all the files before processing them, we lose a lot of the interest of the compression. But it is more open to discussion than what I thought.

**Comment by ftadel** [comment]
And empty room recordings are almost at 50% compression ratio...

**Comment by jasmainak** [comment]
That's quite interesting indeed !
