### ISSUE TITLE
[feature] HED tag validation

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#537]
[HED](http://www.hedtags.org/) tags are an optional part in BIDS data  `.tsv` files. 

It would be nice to validate a potential HED column in a BIDS `.tsv` file while running the bids-validator. Currently, there need to be two steps:

1. Using the BIDS-validator
2. Separately using an HED validation tool, such as provided by the authors of HED: https://github.com/VisLab/HEDTools

Unfortunately, there is no JavaScript HED validation tool at the moment - I am filing this issue regardless to be aware of this opportunity in the future.

**Comment by VisLab** [comment]
We will start to work on a HED validator in this context --- it will take some time.  There are several issues to be addressed.  HED has several levels of validation.

1. Just plain syntax level  (i.e.,  its a comma-separated list of paths with certain types of nesting and parentheses match).  
2. Agrees with a specified version of the HED schema (either exactly or it doesn't contradict, the standard places for extension).  
3. Agrees with specified version but is extended in a non-standard place.  
4. Has all of the required fields (label, description category).  
5. Has correct units for the type in HED or is in the BIDS standard units for things like time, etc.  
6. Doesn't use paradigm tags since BIDS doesn't allow.  
7.  etc....
 
We'll need to discuss this further as we get into it.

**Comment by sappelhoff** [comment]
just referencing the work that is on the way, see: https://www.npmjs.com/package/hed-validator

**Comment by smakeig** [comment]
Kay Robbins and her small team are addressing the validate-in-Javascript problem, though unfortunately the programmer involved is unwell at the moment, she tells me.
