### ISSUE TITLE
Not validating top-level JSONs that are inherited by scans in multiple session configuration

### ISSUE THREAD

**Issue by jpellman** [bids-standard/legacy-validator#62]
The validator says that I need to define 'Repetition Time' for the following NifTI (the directory structure is configured to accommodate multiple visits using 'ses-'):

/sub-A00028185/ses-NFB3/func/sub-A00028185_ses-NFB3_task-DMNTRACKINGTEST_bold.nii.gz

This, however is defined in the following top-level JSON file:

/task-DMNTRACKINGTEST_bold.json

Ditto for other fields ('EchoTime', etc).  I don't get any errors, it just isn't pairing the top-level file with the nested NifTIs.

**Comment by constellates** [comment]
I recreated a minimal dataset with the naming scheme you listed above and did not encounter this issue. The spec requires these properties to be defined in capital case instead of the more JSON-idiomatic camel-case (for example RepetitionTime is valid and repetitionTime isn't). Can you double check if your task-DMNTRACKINGTEST_bold.json follows the capital case convention? And if it does and you're still experiencing this issue are you willing/able to share the contents of task-DMNTRACKINGTEST_bold.json?

**Comment by jpellman** [comment]
The task-DMNTRACKINGTEST_bold.json file does indeed follow capital case.  If you want to take a look at it, it's located at http://s3.amazonaws.com/fcp-indi/data/Projects/RocklandSample/RawDataBIDS/Release6/task-DMNTRACKINGTEST_bold.json .  In the meantime, I'll try re-running the validator to see if I can replicate the issue.

**Comment by constellates** [comment]
Thanks, I'm taking a look now.

**Comment by constellates** [comment]
Looks like the issue is caused by using single quotes for strings (the values for "FlipAngle" and "MagneticFieldStrength") in the JSON file. A lot of systems will coerce single quoted strings to double quoted but only doubles are listed in the JSON spec http://www.json.org/ so I'm questioning whether we should allow them or not.  

You should have seen this error above the Repetition time and other warnings.

```
2: Not a valid JSON file. (code: 27)
    /task-DMNTRACKINGTEST_bold.json
```

Was this JSON file generated automatically by another program or written manually? If it's created by a popular system it might be a case for allowing single quotes.

@chrisfilo do you see any reason for allowing single quoted strings in JSON files?

**Comment by jpellman** [comment]
Thanks @constellates.  The JSON was created using Python's json module-
I'll try using double quotes to see if that solves the issue.

2016-01-04 13:02 GMT-05:00 constellates notifications@github.com:

**Comment by chrisgorgo** [comment]
@constellates let's stick to JSON spec and keep only double quotes.

**Comment by jpellman** [comment]
Double quotes works!  Thanks.

2016-01-04 13:38 GMT-05:00 Chris Filo Gorgolewski notifications@github.com
:

**Comment by constellates** [comment]
No problem.
