### ISSUE TITLE
[Code 26] NIFTI_HEADER_UNREADABLE with symlinks

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#643]
See https://neurostars.org/t/code-26-nifti-header-unreadable/2783 for context. 

This sounds like a regression - symlinked datasets used to work.

**Comment by chrisgorgo** [comment]
@olgn could you have a look?

**Comment by nellh** [comment]
The browser doesn't expose symlinks to web apps, so that seems unlikely.

Maybe the original symlinks are broken or can't be read for the browser? I get this error if I symlink to an NFS mounted nii.gz file that I don't actually have permission to read, for example.

**Comment by olgn** [comment]
I can replicate this error in the manner that @nellh said (permissions error on symlink) - which _should_ raise an error. This permissions error results in `NIFTI_HEADER_UNREADABLE` in the browser but a `FILE_READ` in node, but I think this is due to the difference in file read methods for the different environments.

I have tested bids-validator 1.2.1 in node and browser on datasets with _properly formatted / permissioned symlinks_, and the validator works as expected in both environments.
