### ISSUE TITLE
validator and backwards compatibility

### ISSUE THREAD

**Issue by jasmainak** [bids-standard/legacy-validator#683]
I just [noticed on twitter](https://twitter.com/ChrisFiloG/status/1083737458158772224) that a new version of BIDS has been released. This is great! 

However, this brings back a question I had in my mind for a while and does not go away. Since BIDS is a standard, I would assume that it would stabilize at some point (if yes, when?) or would it keep evolving to adapt to the needs of the community. If it keeps evolving, the practical questions in my mind are:

- what happens to older datasets that were compatible with older versions of BIDS? are authors expected to continually update their datasets just like one updates softwares?
- If not, how does one ensure that the datasets are compatible with older versions? The bids validator is always validating the "dev version" of the BIDS standard.

Shouldn't there be tagged versions of the validator corresponding to different versions of BIDS?

**Comment by chrisgorgo** [comment]
> what happens to older datasets that were compatible with older versions of BIDS?

They remain compatible. Any BIDS 1.x release should be compatible with any other 1.x release.

> are authors expected to continually update their datasets just like one updates softwares?

This should not be necessary. However, there are some special cases:
- A dataset that is BIDS compliant passed the validator due to validator imperfections. A new version of the validator catches the error showing the dataset is invalid. The author should update the dataset.
- The dataset included data types previously not covered by BIDS. When support for those new data types arrives in BIDS the dataset should be updated.

> The bids validator is always validating the "dev version" of the BIDS standard.

This statement is inaccurate. The validator should validate the latest released version of the standard - not the draft.

**Comment by jasmainak** [comment]
> Any BIDS 1.x release should be compatible with any other 1.x release.

I'm not sure I follow. If there is a fix to the standard -- say a metadata field is updated (which is possible?), then how do they remain compatible? I presume the validator is also updated to reflect this? Or do you mean to say that the metadata fields will never be changed/updated in a 1.x release?

> This statement is inaccurate. The validator should validate the latest released version of the standard - not the draft.

Okay, but even if the validator is validating the latest released version and not the dev version, there is still no way to check if an older dataset complies to an older version of the standard, no?
