### ISSUE TITLE
Error: Authors should be array

### ISSUE THREAD

**Issue by zeydabadi** [bids-standard/legacy-validator#697]
I apologize if this is not the right place to post it.

I am using this command in a bash script to create the dataset_description.json

`jo -p "Name"="Human_Prisma" "BIDSVersion"="1.1.0" "License"=" " "Authors"=["Mahmoud Zeydabadinezhad"] "Acknowledgements"=" " "HowToAcknowledge"=" " "Funding"=" " "ReferencesAndLinks"=[" "] "DatasetDOI"=" " >> dataset_description.json`

But the BIDS validator give me this error:

Error 1: [Code 55] JSON_SCHEMA_VALIDATION_ERROR
Invalid JSON file. The file is not formatted according the schema.
Location:

sourcedata/dataset_description.json
Reason:

Invalid JSON file. The file is not formatted according the schema.
Evidence:

.Authors should be array

How should I fix this error?

Thanks,
Mahmoud

**Comment by sappelhoff** [comment]
Hi Mahmoud, could you copy and paste the JSON file that you are validating?

**Comment by nellh** [comment]
It looks like your JSON file has authors as a string containing square brackets, e.g. `Authors: "[Mahmoud Zeydabadinezhad]"` instead of `Authors: [ "Mahmoud Zeydabadinezhad" ]`

You can specify an array of authors like `jo -p Authors[]="Mahmoud Zeydabadinezhad" Authors[]="Another Author"` instead to get the correct output.

**Comment by zeydabadi** [comment]
Thank you, Nell. That solved the problem.
