### ISSUE TITLE
Test suite?

### ISSUE THREAD

**Issue by TheChymera** [bids-standard/legacy-validator#758]
Hi, I am looking to make your software accessible via the Gentoo Linux package manager. How can I run the test suite? I see neither nose, pytest, not unittest in the source code.

**Comment by nellh** [comment]
The Python component doesn't have tests at the moment since it is quite minimal. The JavaScript tests are run with Jest and require Yarn as the entrypoint until [NPM supports workspaces](https://blog.npmjs.org/post/173239798780/beyond-npm6-the-future-of-the-npm-cli).

In the project root: `yarn` will install dependencies into the node_modules directory and `yarn test` will run the JavaScript tests.

**Comment by TheChymera** [comment]
Ah I see, is the js component needed to validate files locally?

**Comment by nellh** [comment]
> Ah I see, is the js component needed to validate files locally?

Yep, the validator is a Node.js application. The Python package just exports some of the regular expressions for use in other tools.

**Comment by TheChymera** [comment]
It turns out the python package is enough to parse BIDS paths locally, if you implement a test suite I'd be happy if you can ping me here :)

**Comment by TheChymera** [comment]
@nellh working on another update to the Gentoo package. I notice there's no mention of `nose` or `pytest` in the package, am I correct to assume there's still no test suite for the Python module?
