### ISSUE TITLE
Need error codes for HED validation errors

### ISSUE THREAD

**Issue by VisLab** [bids-standard/legacy-validator#764]
We are essentially ready to incorporate a first version of syntactic HED validation into the bids-validator.  However, we need to reserve error codes for the following syntax errors and warnings:

**HED syntax errors:**  
* Unsupported character (illegal characters in the HED string, e.g. square and curly brackets)
* Parentheses mismatch
* Missing comma after tag
* First word of tag not capitalized or CamelCase (warning)
* Duplicate tag at top level or in single group
* Too many (more than 2) tildes in a group  

The current version of HED validation does not address validation against a particular HED schema, which is the next step.  We anticipate the following errors for semantic validation, and perhaps this would be a good time to reserve codes for these as well:

**HED semantic errors:**
* commaValid: Previous tag contains a comma when it shouldn’t or tag isn’t valid.
* isNumeric: Invalid numeric tag.
* leafExtension: Extensions are only allowed for leaf tags.
* requireChild: Descendant tag required.
* unique: Multiple unique tags with prefix.
* unitClass: Invalid unit; valid units are…
* invalidTag: Invalid tag.
* required: (WARNING) Tag with prefix <> is required.
* unitClass: (WARNING) No unit specified. Using <> as the default.  

Please let us know how to proceed.

**Comment by sappelhoff** [comment]
Cool! :-)

To proceed, please open a PR introducing several new issue codes. You can use the existing codes as a template. The short descriptions you provided in your issue text here sound intuitive and concise already. This is the file where to introduce the new codes: https://github.com/bids-standard/bids-validator/blob/master/bids-validator/utils/issues/list.js

I am not sure, in how far it makes to introduce these codes ahead of introducing the HED validation code:
- would it make more sense to introduce both at the same time, in a single PR?
- how are we dealing with issue codes that become obsolete? I am looking at [code 100](https://github.com/bids-standard/bids-validator/blob/f9f95e845a6e77da4371b25ca3be6703dcd812d3/bids-validator/utils/issues/list.js#L557) as an example: I introduced it, but shortly after the changes I made had to be reverted because of some clash between web and cmd validator version.

re: "semantic errors" --> I would deal with that when we need it and not before.

Other opinions are appreciated @rwblair @nellh

**Comment by rwblair** [comment]
PR with validation code and errors at the same time makes sense to me. The code to test the error codes will come with the validation code PR, so keeping the two together makes it cleaner.

With regards to deprecated codes, I think commenting that they are deprecated with a link to any relevant discussion in the issues list would be fine. Keeping it in place and visible for future reference might be nice in case it needs to be resurrected or a similar error is being made.
