### ISSUE TITLE
Add command line flag to accept raw data formats that would otherwise raise an error

### ISSUE THREAD

**Issue by CPernet** [bids-standard/legacy-validator#786]
during #OHBM2019 discussion, some users wish to have a flag allowing to ignoring data filename extensions; this applies primarily to non-MRI data for which they may work temporarily with a non-converted format @robertoostenveld

**Comment by sappelhoff** [comment]
Concretely, the discussion was about the EEG extension, where we accept BrainVision, EDF, Biosemi, and EEGLAB data formats, see:

https://github.com/bids-standard/bids-validator/blob/e3c6e4635f077d4b01e7c13baee4a0cf44199c69/bids-validator/bids_validator/rules/file_level_rules.json#L91

The request was to have a command line option like `bids-validator --ignore-extensions my/bids/dataset/path ` that would also accept other data formats. I.e., "pretend" that the raw data files are actually part of the accepted raw data format.

This would be helpful for users who want to adopt BIDS for their internal data organization (**not** sharing), but who do not want to convert all their data.

Personally, I am not a big fan of this approach, but if somebody can propose a reasonable and concrete implementation with the BIDS validator, we can discuss it more.

**Comment by adam2392** [comment]
Hi, BME PhD student, (primarily using Python for ECoG/SEEG analysis, with some scalp EEG in there), here with some thoughts:

 I took a look at these things linked to me by @jasmainak:

- bids-standard/bids-validator#786 and
- https://github.com/mne-tools/mne-bids/pull/285

1. I am in favor of adding this command line flag because converting datasets takes a long time, and I (as an example) have already converted a lot of my data from `edf` to `fif` because of the fact that MNE-Python basically uses primarily `fif`.  The reason I did this was because the EDF files had small errors in formatting say clinical annotations, or channel labeling, which was all primarily due to conversion from a proprietary format like Nihon Kohden, or Natus iEEG/EEG systems. 

Hacking and adjusting metadata within an EDF file is also non-arbitrarily done and can't be done in the context of MNE-Python (at least to my knowledge). Thus, if you need to clean up your datasets, you either need to do it manually, or FIF (done in MNE-Python), or BV (done in MNE-BIDS).

Having to now double check say all 100 subjects I have just as BV because that is the format that seems to have been decided currently in MNE-BIDS, seems like a huge pain rather than pro of the BIDS format. I actually think the BIDS is the best format I've seen so far, which is why I've spent some effort converting my datasets into this standard. But having this flag seems like an "intermediary" step to helping people convert to BIDS while the software catches up. 

2. In addition, it is not so clear to me why FIF is not used, when you look at: https://bids.berkeley.edu/news/bids-megeegieeg-data-format-survey

If you take a look at ECoG and SEEG, BV is far behind FIF in terms of usage.

I'm a "new-user" to BIDS, so perhaps my understanding is a bit behind and if I'm missing any details, let me know.

**Comment by robertoostenveld** [comment]
Let me first answer your question 1:  I think it is a bad idea to add exceptions to the bids-validator that have to be explicitly processed by the code. The desired functionality has already been implemented by means of the `.bidsignore` file. So rather than adding the exception-handling to the validator, the exceptions are listed as part of the dataset. This not only keeps the code clean from specific exception handling, but also ensures that it works when running in a web browser (e.g. upon upload to openneuro) where command line options cannot be passed.

Please try adding the to-be-ignored file extension to `.bidsignore` in your dataset and try whether the validation of your dataset passes.

**Comment by robertoostenveld** [comment]
Regarding your 2nd question: that is not really appropriate for this github issue, which is a request to add some option to the bids-validator (i.e. the software). Your question about the specification is more appropriate on Neurostars or on the bids-discussion google group. Github issues is not a community support channel

But nevertheless a short answer from my point of view: FIF is supported as MEG format because it is the native format of the Megin/Elekta/Neuromag system. FIF is not a file format native to intracranial EEG data: there is no vendor software that exports iEEG data in the FIF format. More appropriate might be to ask why your native iEEG format (which is not FIF, but some format of a clinical system)  is not supported. Also, BIDS is (so far) about raw data, and you processing it in Python suggests that the data you want to store is not raw any more. Exporting from Python to a BIDS compliant format (without loss of information) is possible with [bids-standard/pybv](https://github.com/bids-standard/pybv).

**Comment by CPernet** [comment]
+1 `.bidsignore` is there for that

**Comment by jasmainak** [comment]
Sorry to pitch in late here. I'm not sure `.bidsignore` can solve the same issue. Because what `.bidsignore` does is ignore the files altogether. What users are asking for is to ignore only a specific part of the filename, not the entire file. This way, you can still use tools like PyBIDS to find entities etc.

**Comment by effigies** [comment]
`.bidsignore` is a bids-validator concept, not pybids.

**Comment by jasmainak** [comment]
sure, but what I'm trying to say is that `.bidsignore` should be used as a last resort because it makes large parts of the data unusable. A command line flag is less brutal and leaves the data amenable to tools like pybids
