### ISSUE TITLE
Acknowledge version control

### ISSUE THREAD

**Issue by mih** [bids-standard/legacy-validator#79]
The validator complains about a present .git directory. It would be useful to have it ignore Git or SVN (etc.) files and directories. Reporting each of those files can easily yield several thousand reports and clutter the output.

**Comment by constellates** [comment]
I'm guessing this could be related to #78 as well. If version control is tripping the quick test we definitely should be more verbose about it. 

@chrisfilo let us know your thoughts on allowing version control in datasets.

Somewhat related, I've often seen warnings caused by .DS_Store files that are created by OSX when files are moved. I assume other OS's do something similar. They generally throw a warning to the effect of "This file is not a part of the BIDS dataset". Should these be treated differently?
