### ISSUE TITLE
Use "master" of bids-validator in Continuous Integration (Travis=Unix, Appveyor=Windows)

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#790]
# What I need

I want to make `bids-validator` globally available from the command line in the version that corresponds to the current state of the git repository (`master`)

# Some history

We used to be able to install the development version of `bids-validator` via `npm` and as such get the latest version through: `npm install https://github.com/bids-standard/bids-validator.git`

This would achieve what I need.

# The problem

Now we are installing the development version using `yarn` ... and with `yarn` there does not seem to be an easy way as previously with `npm` - or at least I did not find it yet.

I tried `yarn add <github url>`, as described [here](https://stackoverflow.com/a/43565045/5201771) but got this error:

```Text
(base) stefanappelhoff@arc-lin-004309:~$ yarn add https://github.com/bids-standard/bids-validator
yarn add v1.16.0
info No lockfile found.
[1/4] Resolving packages...
error Can't add undefined: invalid package version undefined.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

```

Can I get some help, perhaps by @nellh who helped on a similar issue a while ago? https://github.com/bids-standard/bids-validator/issues/723#issuecomment-467340448

**Comment by nellh** [comment]
There's a couple ways of doing this. One is to git clone and `cd bids-validator/bids-validator` then run npm or yarn install in the package directory rather than the git root.

The other thing we could do is publish the master branch as a pre-release on npm for each commit. bids-validator@next for example. Then you could install that latest build with `npm install bids-validator@next`

**Comment by sappelhoff** [comment]
> There's a couple ways of doing this. One is to git clone and cd bids-validator/bids-validator then run npm or yarn install in the package directory rather than the git root.

would this provide me with a globally available `bids-validator` command?

or would I need to call `./bids-validator/bids-validator/bin/bids-validator`? (where the first `bids-validator` is my cloned directory)

**Comment by nellh** [comment]
You can use the `-g` flag with npm (but not yarn). Global installs are generally discouraged since it is easy to end up with multiple conflicting versions or dependencies modified by other packages but it should work. You can also add your `node_modules/.bin` directory to your PATH environment variable to use a non-global install without typing the full path.

**Comment by sappelhoff** [comment]
thanks!

Some more notes: I need to do this for running `bids-validator` in continuous integration services

- travis ... see current script: https://github.com/mne-tools/mne-bids/blob/a1f3288871eea49cfdaead0b20000570044fc62b/.travis.yml#L27
- appveyor ... see current script: https://github.com/mne-tools/mne-bids/blob/a1f3288871eea49cfdaead0b20000570044fc62b/appveyor.yml#L26


> You can also add your node_modules/.bin directory to your PATH environment variable to use a non-global install without typing the full path.

this sounds like a good idea! I'll try it on Monday.

**Comment by sappelhoff** [comment]
# Update

### unix

with the help of @jasmainak and @larsoner I got this to work in our [travis script](https://github.com/mne-tools/mne-bids/blob/8c5c956524ab0155888ce5f230e7825a42b34f81/.travis.yml) as such:

```shell
   - |
      if [ $VALIDATOR_VERSION == 'master' ];then
          pushd ~
          git clone --depth 1 https://github.com/bids-standard/bids-validator
          cd bids-validator
          yarn
          export PATH=~/bids-validator/bids-validator/bin:$PATH
          popd
      elif [ $VALIDATOR_VERSION == 'stable' ];then
          npm install -g bids-validator
      else
          echo "VALIDATOR_VERSION should be set to master or stable"
          echo "but VALIDATOR_VERSION=$VALIDATOR_VERSION"
      fi


```

### windows

For our Windows CI ([Appveyor script](https://github.com/mne-tools/mne-bids/blob/8c5c956524ab0155888ce5f230e7825a42b34f81/appveyor.yml)), I still run into problems. So I tried to get the development version of BIDS-validator to run locally on my Windows partition.

First, I needed to install the following (and make them available as executables from cmd)

- python2
- python3
- nodejs (version 10.0.0 ... higher versions break!!!)
- yarn
- `npm i -g --production windows-build-tools`

now I finally got the installation to work out well ... and I wanted to test my executable located in `bids-validator/bids-validator/bin` ... but when trying to call it, all I get is:

`'bids-validator' is not recognized as an internal or external command,
operable program or batch file.`

which [corresponds to the error I get on appveyor](https://ci.appveyor.com/project/mne-tools/mne-bids/builds/25500525#L51)

Do you have any idea how to proceed @nellh ? Is `bids-validator` even "fit" to be installed/handles on Windows using the development version?

**Comment by nellh** [comment]
There was a PR to [implement Appveyor support](https://github.com/bids-standard/bids-validator/pull/225/files) but it was not merged. That might shed some light on a solution?

Since we don't have tests for Windows support I would not be surprised if it is broken at the moment.

One thing I'd suggest is running it with `node ./bin/bids-validator` to see if that even works on Windows.

**Comment by sappelhoff** [comment]
indeed, `node ./bin/bids-validator` works as expected!

**Comment by sappelhoff** [comment]
Thanks for now @nellh!
