### ISSUE TITLE
Profile IO operations.

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#807]
Validator may be hitting filesystems too hard:
https://github.com/OpenNeuroOrg/openneuro/issues/1219

**Comment by nellh** [comment]
Specifically we're seeing this on NFSv4 with datasets that have many (200+) participants.

**Comment by nellh** [comment]
The worst case dataset spends 65% of the time running lstat syscalls in https://github.com/bids-standard/bids-validator/blob/master/bids-validator/utils/files/readDir.js#L129 - 25% is spent on the actual readdir calls. We do make an extra lstat call for every annexed file (since they are symlinks), which could be avoided for OpenNeuro where directories will never be symlinks but is useful generally.

**Comment by nellh** [comment]
I think this is solved for now.
