### ISSUE TITLE
Refactor remote validation test suite to reduce run time

### ISSUE THREAD

**Issue by ckrountree** [bids-standard/legacy-validator#818]
Now that we have moved hosting to EFS, this code may never be necessary and it currently affects test performance considerably.  We recommend removing this chunk of code and it's refactor.

**Comment by nellh** [comment]
Just to be clear, this was to support a feature in OpenNeuro which has evolved to probably not require this bids-validator feature. Do we think this is generally useful?

**Comment by rwblair** [comment]
Months ago we had talks with people over at the NDA project (https://nda.nih.gov/) about using bids-validator when they're ingesting datasets. They use S3 credential federation to allow users to upload directly to their s3 accounts. They would like the ability to validate S3 repos remotely so that they did not have to download datasets for just validation.

To document it, what were the major issues with keeping remote validation in the validator? I'm just now starting to read through the remoteFiles code to get a sense of how it works so I don't have good intuition for what the problems might be.

**Comment by ckrountree** [comment]
Let's mock this up...

**Comment by ckrountree** [comment]
Decision not to remove it and put some time into improving tests.

**Comment by nellh** [comment]
The test suite is pretty fast on Linux but it needs improvement to run efficiently on macOS and WIndows.

**Comment by ckrountree** [comment]
This piece of the ticket has been completed.  There could still use some refactoring.  Therefore, opened a new ticket - bids-standard/bids-validator#876, which may only affect performance.
