### ISSUE TITLE
hardcoded paths and a test that should be failing

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#85]
I recently noticed that a path in one of the tests is hardcoded to a value that works only on @constellates workstation. Despite that fact the tests are still passing (both on my machine and on CircleCI) even though they should fail, because the file does not exists. Maybe for some reason the callback with the assert was not called?

**Comment by constellates** [comment]
My bad, I see a couple and will fix those. The reason they work however it because they're being used as mock file definitions. So those particular tests are only testing functionality that happens after the file reading process would already have taken place. It makes it a little easier to target specific file conditions so we don't have to create and manage actual files for every issue.
