### ISSUE TITLE
BIDS Validator web version slow

### ISSUE THREAD

**Issue by dlevitas** [bids-standard/legacy-validator#884]
Hi,

I'm trying to validate a set of 23 subjects using the the BIDS validator web (v1.3.12); however, it has spent the last hour loading without any sign of completion. I've had this issue in the past when trying to validate datasets with 10+ subjects, so I wanted to raise the issue. For now, I'll use the command line method for validation.

Dan

**Comment by nellh** [comment]
Thanks for the report! Can you describe dataset which you ran into the issue? It would be helpful to know total size in bytes and total file count. What browser version you are using and how much memory does your system have?

**Comment by dlevitas** [comment]
I'm using this [validator](https://bids-standard.github.io/bids-validator/) (v1.3.12) through Firefox. The size of the dataset is 48Gb (478 files), and I'm working on this through my university's HPC, so memory isn't an issue for me.

**Comment by nellh** [comment]
It's useful to know the total system memory where the browser is running because browsers allocate page quotas based on a percentage of the total system memory, to prevent memory overuse by one page. The web validator could be hitting this memory quota and hanging in this case.

You can get the exact value from Firefox by opening the developer console and running this:
`await navigator.storage.estimate().then(estimate => estimate.quota)`

**Comment by dlevitas** [comment]
Ah, okay. The output from that command is 2147483648

**Comment by sappelhoff** [comment]
closing for staleness reasons, please reopen if this is still an issue
