### ISSUE TITLE
Web validator considers top level sessions.json invalid

### ISSUE THREAD

**Issue by lchiou** [bids-standard/legacy-validator#888]
The [web validator](http://bids-standard.github.io/bids-validator/) gives a "[Code 1] NOT_INCLUDED" error when I have a `sessions.json` data dictionary in my top-level directory (corresponding to all `sub-*/sub-*_sessions.tsv` files).

**Comment by sappelhoff** [comment]
Sorry for the late reply. Your problem is due to this line in the code:

https://github.com/bids-standard/bids-validator/blob/a6d9ada59b8628a52520bae96f5f45eb61f86a79/bids-validator/bids_validator/rules/subject_level_rules.json#L3

the validator expects `sessions.json` files to be subject specific. Instead of supplying a single `sessions.json` file at the root, please define a `sub-<label>_sessions.json` file for each subjects.

I know that this sometimes leads to unnecessary duplication, but it's the way to go for now.

We have recently discussed this problem also with regards to `events.json` and `coordsystem.json`, see:

- https://github.com/bids-standard/bids-validator/issues/1039
- https://github.com/bids-standard/bids-specification/issues/528
