### ISSUE TITLE
Validator-recommended Name is not read

### ISSUE THREAD

**Issue by jbteves** [bids-standard/legacy-validator#895]
When missing a task file (error Error 1: [Code 50] TASK_NAME_MUST_DEFINE), the validator recommends the following as an option:
```
/sub-VR449TVV/ses-fmri01/func/sub-VR449TVV_ses-fmri01_task-rest_bold.json
```
However, when I create that filename, the validator repeats the same error message, including a recommendation that I create that same filename. I am not sure if that is indeed a valid BIDS filename, however, the validator should not recommend a filename that it itself does not see as valid. The file is valid JSON, albeit placeholder info while I try to get the validator to accept my input.

**Comment by rwblair** [comment]
Believe this was because 'TaskName' was not defined as 'rest' inside the json file rather than the task name used in the task label:
https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#required-fields

@jbteves if the json file had the correct TaskName field let me know and I can look into it further.
