### ISSUE TITLE
bids-validator in Python for Windows OS

### ISSUE THREAD

**Issue by JegouA** [bids-standard/legacy-validator#928]
Hello,

I am working on Windows OS and I had difficulty using bids-validator python package. 
bids-validator couldn't match my path with the rules. I changed the separator of my path '\\' in '/'  and it seems working now.

I just don't know if it's the best solution. Do you know a better solution?

Thank you
Aude

**Comment by sappelhoff** [comment]
Sounds like the python code uses hard coded separator strings like `/` instead of using `os.path.sep` 🤔 

see e.g.: https://github.com/bids-standard/bids-validator/blob/920d1957c1788c96f3df5b0be3eb7c2be594f8d3/bids-validator/bids_validator/bids_validator.py#L36

If that's the issue, it could be fixed in all `.py` files

**Comment by sappelhoff** [comment]
Hi @JegouA

- did your initial fix completely solve your problem, or did it reoccur later?
- @rwblair are we continuously testing the python validator on all three common OSses?

**Comment by nellh** [comment]
The Python component is not tested, though the underlying regular expressions that are the majority of the logic are covered by the JavaScript test suite. CI is only run on Windows and Linux, there is no macOS CI setup currently.

**Comment by JegouA** [comment]
Hello @sappelhoff 

My initial fix completely solves the problem but I didn't change the python script of bids_validator.
I change the separator of my path before giving it to bids validator.

Thank you
