### ISSUE TITLE
Multi-level JSON schemas

### ISSUE THREAD

**Issue by EDRasmussen** [bids-standard/legacy-validator#930]
Hello,

I currently have made a change in the bids-validator\bids-validator\validators\json\json.js to include files which paths ends with pet.json so it will check the PET scan json files as well as made a pet.json schema in the schemas folder.

The problem I'm facing now is that the current standard for the PET scan data is that it's multi-level, where other data is flat. This is in the sense that you have an "Info" object which contains a values and other objects. Currently, when checking other schemas, the only have a way they check the values inside other objects is to use the AnyOf function where you can give it data types etc. While I guess this would work it would be far from ideal as I also don't think it's possible to set required data fields to be the member variables of objects.

So my question is if this is possible or the standard would have to be reworked to be a flat structure instead of the multi-level way it is done today.

I used the following dataset for testing: https://openneuro.org/datasets/ds001421

**Comment by sappelhoff** [comment]
Hi @Niveauet, could you supply a minimal example to illustrate your point? Perhaps something that can be posted right in this thread using the [code formatting in markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)?

**Comment by EDRasmussen** [comment]
Yes of course. This is an execerpt from the dataset for PET scan files:

```javascript
{ 
  "Info": {
    "Tomograph": ["HRRT"],
    "BodyPart": ["brain"],
    "Unit": ["Bq/ml"],
    "Tracer": {
      "MW": [],
      "InjectionType": ["bolus"],
      "Isotope": ["C-11"],
      "Name": ["[C-11]SB"]
    }
  },
  "RadioChem": {
```

as we can see here the data is "multi-level" in the sence that the Info (and by extension Tracer) object contains other values that we want to validate as well.

If we look at another json file, for example from anat we can see that the data doesn't have these multiple levels:

```javascript
{
	"Modality": "MR",
	"MagneticFieldStrength": 3,
	"Manufacturer": "Siemens",
	"ManufacturersModelName": "Trio",
	"InstitutionName": "Redacted",
	"InstitutionAddress": "Redacted",
	"DeviceSerialNumber": "Redacted",
	"StationName": "Redacted",
	"ProcedureStepDescription": "Redacted",
	"SoftwareVersions": "syngo_MR_A30_4VA30A",
```

This is true for all other types of data sets and as such I don't have an example to go for when implementing the validation for the PET scan datasets.

**Comment by sappelhoff** [comment]
Ahh I see, thanks for the examples.

In EEG there are the "Filter" fields, which are also nested, for example:

```
{
    "HardwareFilters": {
        "Highpass RC filter": {
            "Half amplitude cutoff (Hz)": 0.0159,
            "Roll-off": "6dB/Octave"
        }
    },
    "SoftwareFilters": "n/a"
}
```

see [bids-starter-kit](https://github.com/bids-standard/bids-starter-kit/blob/master/templates/sub-01/ses-01/eeg/sub-01_ses-01_task-FilterExample_eeg.json)

This is how it is implemented in a JSON schema:

https://github.com/bids-standard/bids-validator/blob/306a8cd002e7aa713a1a9374338451f4faf14974/bids-validator/validators/json/schemas/eeg.json#L30-L32

Note also this discussion, which is also about multilevel JSONs and TSVs:

https://github.com/bids-standard/bids-starter-kit/pull/130

**Generally** though I would advise you to study https://json-schema.org/ to find a solution, because presently there are no good solutions that are as fully worked out as you would need it. So nothing to do an easy copy/paste on, unfortunately :-/

If you need more help, we can maybe ping some other developers.

**Comment by sappelhoff** [comment]
@Niveauet did you make any progress on this?

**Comment by sappelhoff** [comment]
Closing now, please reopen with new input / information if this is still on your mind @Niveauet.

Or tell us how you solved your problems and leave the issue closed.

Thanks!
