### ISSUE TITLE
Validator error with iEEG data in MEF3 format 

### ISSUE THREAD

**Issue by dorahermes** [bids-standard/legacy-validator#953]
I am preparing a BIDS-iEEG dataset to share on OpenNeuro. Some of my iEEG data are in MEF3 format, which should currently be allowed (but not supported) and maybe give a warning, but not an error. The validator does however not recognize the _ieeg.mefd file as BIDS-compatible and gives errors. 

@sappelhoff @maxvandenboom

**Comment by sappelhoff** [comment]
Hi @dorahermes that is because `mefd` files are not in the list of regular expressions, currently I see only `mef` there 🤔 

so is `mef` wrong and it should be `mefd`? Or does the MEF3 format have several file extensions?

https://github.com/bids-standard/bids-validator/blob/1888b87268c8f4bff26e073a96191dccca137e60/bids-validator/bids_validator/rules/file_level_rules.json#L180-L189

PS: Great to get some MEF3 data openly shared in BIDS 👍

**Comment by dorahermes** [comment]
Ah, thanks @sappelhoff that's it:  "mef" should be "mefd".

PS. I am really enjoying working with MEF3 data, since it allows for indexing and loading parts of the data so I can very easily work with much larger datasets)

**Comment by dorahermes** [comment]
I opened a pull request #954 to resolve

**Comment by sappelhoff** [comment]
I just realized that we may have to adjust the validator further and tell it that `mefd` "files" are actually directories.

Same as for MEG `.ds` directories:

https://github.com/bids-standard/bids-validator/blob/6a937a1ba1d08d3e14d3f0c984ab6ba8a7f7a9fd/bids-validator/utils/bids_files.js#L66-L78

But we can wait for Dora to confirm / dis-confirm that validation is working now (in the `master` version of the validator)

I think this link should lead to the "master" web validator: https://4930-37161308-gh.circle-artifacts.com/0/%7E/web_version/index/index.html

**Comment by dorahermes** [comment]
I can not confirm that validation is working yet at the link to the  "master" web validator is not working for me. What would be the best way to test? 

I can also prepare an example empty dataset and share on github.

**Comment by sappelhoff** [comment]
Mmh if the web "master" validator is not working, you could install the command line "master" validator, using [these instructions](https://github.com/bids-standard/bids-validator/blob/master/CONTRIBUTING.md#using-the-development-version-of-bids-validator).

Or perhaps @nellh can tell us how we can use the "master" version of the validator, if at all possible? (E.g. a circleci artifact or similar?)

Other options:
1. wait for a new release of the validator

**Comment by sappelhoff** [comment]
I talked about this with @rwblair today and the web master validator may be available in the future, but (probably) not now.

so trying to use the command line master validator seems like the best option for now.

**Comment by dorahermes** [comment]
I have an updated fork with the bids-validator and ran yarn to install the bids-validator and added this path in my .bashrc. However, I am not sure whether how to actually run the github/development version, since I also already had installed the validator through the command line before (current version 1.5.3) by npm install -g bids-validator... I am sorry for being such a newbie here, but I actually do not know and have not yet been able to figure out how to uninstall the npm installed validator, such that I can run the github version...

**Comment by sappelhoff** [comment]
`npm uninstall -g bids-validator` should remove your previously install bids-validator.

Then to check if you are actually using bids-validator from your cloned GitHub fork (that you updated to bids-standard/bids-validator), do the following:

1. open a new terminal
1. run `bids-validator --version` ... should be 1.5.3
1. `cd` to your `bids-validator` directory (your clone of your fork)
1. run `git checkout 1.2.4`
1. run `bids-validator --version` again ... should be 0.0.0 ... now the version doesn't make sense but the fact that the output of bids-validator changed after you made a change to the `bids-validator` directory (through `git checkout`) is proof that you are using that directory

now if this was successful, `git checkout master` again in your `bids-validator` ... and always keep it up to date with bids-standard/bids-validator.

Let me know if that helped

**Comment by dorahermes** [comment]
Thanks @sappelhoff !

We still get an error with .mefd file folders @maxvandenboom is looking at how to fix this and may do a pull request/or come back with some questions.

**Comment by sappelhoff** [comment]
sounds great :-) I think it has something to do with the fact that `mefd` is a directory, but currently handled the same way as a file.

perhaps what I wrote in https://github.com/bids-standard/bids-validator/issues/953#issuecomment-626208416 is helpful @maxvandenboom

**Comment by MaxvandenBoom** [comment]
Hi everyone!

I created a pull request https://github.com/bids-standard/bids-validator/pull/958 to solve the issue.
- bids-validator/bids-validator/bids_validator/rules/file_level_rules.json
@dorahermes The regex adjustment to 'mefd' was almost it, but there was a nuance. The "mefd" in the regex is about files, the MEF3 format only has a directory with .mefd, so the files inside of this directory continued to produce errors. I made a quick fix so the regex is ok with files in a .mefd directory

- bids-validator/bids-validator/utils/bids_files.js
 @sappelhoff Thanks for the hint and your efforts! When I run the validator from the command-line, it does not pass that function. But since it might be reached in other ways, I did add support for a .mefd directory in the same way as the .ds directory is accepted for MEG.

I tested it on MEF3 data and it works now.

Best regards,
Max
